"""Pydantic schemas for OpenAI-compatible API and internal server management endpoints."""

import time
import uuid
from typing import List, Optional, Union
from pydantic import BaseModel, Field


# --- OpenAI Tool / Function Calling Schemas ---

class ToolFunction(BaseModel):
    """Function specification within a tool definition."""
    name: str = Field(..., description="Name of the function to call.")
    description: Optional[str] = Field(None, description="Description of what the function does.")
    parameters: Optional[dict] = Field(None, description="JSON Schema object describing function parameters.")


class ToolDefinition(BaseModel):
    """Tool definition shape matching OpenAI spec."""
    type: str = Field("function", description="Type of tool (e.g. function).")
    function: ToolFunction = Field(..., description="Function definition.")


class FunctionCall(BaseModel):
    """Function call invocation shape."""
    name: str = Field(..., description="Name of function called.")
    arguments: str = Field(..., description="JSON string of arguments passed to function.")


class ToolCall(BaseModel):
    """Tool call payload matching OpenAI tool_calls structure."""
    id: str = Field(default_factory=lambda: f"call_{uuid.uuid4().hex[:12]}")
    type: str = Field("function", description="Type of tool call.")
    function: FunctionCall = Field(..., description="Function call payload.")


# --- OpenAI Chat Completion Request Schemas ---

class ChatMessage(BaseModel):
    """Chat message with role, content, and optional tool_calls or tool_call_id."""
    role: str = Field(..., description="Role of the message author (e.g. system, user, assistant, tool).")
    content: Optional[str] = Field("", description="Contents of the message.")
    tool_calls: Optional[List[ToolCall]] = Field(None, description="Tool calls generated by the assistant.")
    tool_call_id: Optional[str] = Field(None, description="Tool call ID associated with tool output message.")


class ChatCompletionRequest(BaseModel):
    """OpenAI-compatible chat completion request."""
    model: str = Field("default", description="Model identifier requested.")
    messages: List[ChatMessage] = Field(..., description="List of messages comprising the conversation.")
    max_tokens: Optional[int] = Field(256, description="Maximum number of tokens to generate.")
    temperature: Optional[float] = Field(1.0, description="Sampling temperature.")
    stream: Optional[bool] = Field(False, description="Whether to stream back partial progress via SSE.")
    stop: Optional[Union[str, List[str]]] = Field(None, description="Optional stop sequence(s).")
    tools: Optional[List[ToolDefinition]] = Field(None, description="List of tools the model may call.")
    tool_choice: Optional[Union[str, dict]] = Field(None, description="Controls which (if any) tool is called.")


# --- OpenAI Chat Completion Response Schemas ---

class ChatCompletionChoiceMessage(BaseModel):
    """Assistant message in a completion choice."""
    role: str = "assistant"
    content: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None


class ChatCompletionChoice(BaseModel):
    """Completion choice object."""
    index: int = 0
    message: ChatCompletionChoiceMessage
    finish_reason: Optional[str] = "stop"


class CompletionUsage(BaseModel):
    """Token usage telemetry."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class ChatCompletionResponse(BaseModel):
    """OpenAI-compatible chat completion response."""
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:12]}")
    object: str = "chat.completion"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = "apah-model"
    choices: List[ChatCompletionChoice]
    usage: CompletionUsage


# --- OpenAI Streaming Chunk Schemas ---

class ChatCompletionChunkDelta(BaseModel):
    """Delta payload in streaming response chunk."""
    role: Optional[str] = None
    content: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None


class ChatCompletionChunkChoice(BaseModel):
    """Choice chunk payload in streaming response."""
    index: int = 0
    delta: ChatCompletionChunkDelta
    finish_reason: Optional[str] = None


class ChatCompletionChunk(BaseModel):
    """OpenAI-compatible streaming response chunk."""
    id: str = Field(default_factory=lambda: f"chatcmpl-{uuid.uuid4().hex[:12]}")
    object: str = "chat.completion.chunk"
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str = "apah-model"
    choices: List[ChatCompletionChunkChoice]


# --- OpenAI Embedding Schemas ---

class EmbeddingRequest(BaseModel):
    """OpenAI-compatible embedding request payload."""
    model: str = Field("default", description="Model ID to use for generating embeddings.")
    input: Union[str, List[str]] = Field(..., description="Input text or array of texts to embed.")
    encoding_format: Optional[str] = Field("float", description="Encoding format for embeddings (e.g. float).")


class EmbeddingData(BaseModel):
    """Embedding vector object."""
    object: str = "embedding"
    embedding: List[float] = Field(..., description="Embedding vector.")
    index: int = Field(..., description="Index of input text in request array.")


class EmbeddingResponse(BaseModel):
    """OpenAI-compatible embedding response payload."""
    object: str = "list"
    data: List[EmbeddingData]
    model: str
    usage: CompletionUsage


# --- Internal Server Management Schemas ---

class LoadModelRequest(BaseModel):
    """Request payload for loading a model into the runtime."""
    model_path: str = Field(..., description="Hugging Face model ID or local directory path.")
    dtype: str = Field("bfloat16", description="Data type for model weights (bfloat16, float16, float32).")
    device: str = Field("cuda", description="Target GPU execution device (e.g. cuda, cuda:0).")
    tp_world_size: int = Field(1, description="Tensor parallel world size (number of GPUs).")


class ModelStatus(BaseModel):
    """Status telemetry for loaded model and scheduler."""
    name: str = Field(..., description="Name or path of loaded model.")
    loaded: bool = Field(..., description="Whether a model is currently loaded.")
    gpu_memory_mb: float = Field(..., description="Current GPU memory allocated in MB.")
    uptime_seconds: float = Field(..., description="Seconds elapsed since model was loaded.")
    idle_seconds: float = Field(0.0, description="Seconds elapsed since last request activity.")
    active_batch_size: int = Field(0, description="Number of currently active sequences in batch.")
    waiting_queue_length: int = Field(0, description="Number of sequences waiting in queue.")
    aggregate_throughput_tok_s: float = Field(0.0, description="Aggregate tokens/sec throughput across batch.")
    tp_world_size: int = Field(1, description="Tensor parallel world size (number of GPUs).")
    gpu_devices: List[int] = Field(default_factory=lambda: [0], description="List of GPU device indices occupied by model.")


class GPUStatsResponse(BaseModel):
    """Real-time GPU hardware metrics response payload."""
    index: int
    name: str
    memory_used_mb: float
    memory_total_mb: float
    memory_free_mb: float
    utilization_pct: float
    temperature_c: float


# --- OpenAI Error Response Schemas ---

class OpenAIError(BaseModel):
    """Standard OpenAI error shape."""
    message: str
    type: str = "invalid_request_error"
    param: Optional[str] = None
    code: Optional[str] = None


class OpenAIErrorResponse(BaseModel):
    """Top-level OpenAI error response wrapper."""
    error: OpenAIError

